"use client"

import { useState } from "react"
import {
  FileText,
  Download,
  Languages,
  Check,
  FileType,
  Loader2,
} from "lucide-react"
import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { cn } from "@/lib/utils"

interface Finding {
  id: string
  title: string
  description: string
  severity: "normal" | "mild" | "moderate" | "severe"
  location: string
}

interface Disease {
  name: string
  confidence: number
  description: string
}

interface AnalysisResult {
  findings: Finding[]
  impression: string
  diseases: Disease[]
  metadata: {
    scanType: string
    sliceCount: number
    dimensions: string
    patientId: string
    studyDate: string
  }
}

type Language = "en" | "fr" | "ar"
type ExportFormat = "pdf" | "docx"

const languageLabels: Record<Language, { name: string; flag: string; dir: "ltr" | "rtl" }> = {
  en: { name: "English", flag: "GB", dir: "ltr" },
  fr: { name: "Francais", flag: "FR", dir: "ltr" },
  ar: { name: "العربية", flag: "DZ", dir: "rtl" }
}

// Translations for report content
const translations: Record<Language, {
  title: string
  patientId: string
  studyDate: string
  scanType: string
  findings: string
  impression: string
  aiDetection: string
  confidence: string
  location: string
  severity: {
    normal: string
    mild: string
    moderate: string
    severe: string
  }
  generatedBy: string
  disclaimer: string
}> = {
  en: {
    title: "Medical Imaging Report",
    patientId: "Patient ID",
    studyDate: "Study Date",
    scanType: "Scan Type",
    findings: "Findings",
    impression: "Impression",
    aiDetection: "AI Detection Results",
    confidence: "Confidence",
    location: "Location",
    severity: {
      normal: "Normal",
      mild: "Mild",
      moderate: "Moderate",
      severe: "Severe"
    },
    generatedBy: "Generated by MedVision AI",
    disclaimer: "This report was generated by artificial intelligence and should be reviewed by a qualified medical professional."
  },
  fr: {
    title: "Rapport d'Imagerie Medicale",
    patientId: "ID Patient",
    studyDate: "Date de l'etude",
    scanType: "Type de Scan",
    findings: "Resultats",
    impression: "Impression",
    aiDetection: "Resultats de Detection IA",
    confidence: "Confiance",
    location: "Localisation",
    severity: {
      normal: "Normal",
      mild: "Leger",
      moderate: "Modere",
      severe: "Severe"
    },
    generatedBy: "Genere par MedVision AI",
    disclaimer: "Ce rapport a ete genere par intelligence artificielle et doit etre examine par un professionnel medical qualifie."
  },
  ar: {
    title: "تقرير التصوير الطبي",
    patientId: "رقم المريض",
    studyDate: "تاريخ الدراسة",
    scanType: "نوع الفحص",
    findings: "النتائج",
    impression: "الانطباع",
    aiDetection: "نتائج الكشف بالذكاء الاصطناعي",
    confidence: "نسبة الثقة",
    location: "الموقع",
    severity: {
      normal: "طبيعي",
      mild: "خفيف",
      moderate: "متوسط",
      severe: "شديد"
    },
    generatedBy: "تم إنشاؤه بواسطة MedVision AI",
    disclaimer: "تم إنشاء هذا التقرير بواسطة الذكاء الاصطناعي ويجب مراجعته من قبل متخصص طبي مؤهل."
  }
}

// Translate findings and diseases
const translateFinding = (finding: Finding, lang: Language): Finding => {
  if (lang === "en") return finding
  
  const frTranslations: Record<string, { title: string; description: string }> = {
    "White Matter Hyperintensities": {
      title: "Hyperintensites de la Substance Blanche",
      description: "Foyers multiples d'hyperintensite T2/FLAIR dans la substance blanche periventriculaire, representant probablement des modifications ischemiques microvasculaires chroniques."
    },
    "Mild Ventricular Enlargement": {
      title: "Elargissement Ventriculaire Leger",
      description: "Les ventricules lateraux semblent legerement proeminents, probablement une perte de volume liee a l'age."
    },
    "No Acute Infarct": {
      title: "Pas d'Infarctus Aigu",
      description: "Aucune preuve de modifications ischemiques aigues sur l'imagerie ponderee en diffusion."
    },
    "No Hemorrhage": {
      title: "Pas d'Hemorragie",
      description: "Aucune preuve d'hemorragie intracranienne ou d'effet de masse."
    }
  }
  
  const arTranslations: Record<string, { title: string; description: string }> = {
    "White Matter Hyperintensities": {
      title: "فرط كثافة المادة البيضاء",
      description: "بؤر متعددة صغيرة من فرط الكثافة T2/FLAIR في المادة البيضاء حول البطينين، من المحتمل أن تمثل تغيرات إقفارية وعائية دقيقة مزمنة."
    },
    "Mild Ventricular Enlargement": {
      title: "توسع بطيني خفيف",
      description: "البطينان الجانبيان يبدوان بارزين قليلاً، من المحتمل أن يكون فقدان حجم مرتبط بالعمر."
    },
    "No Acute Infarct": {
      title: "لا يوجد احتشاء حاد",
      description: "لا دليل على تغيرات إقفارية حادة في التصوير المرجح بالانتشار."
    },
    "No Hemorrhage": {
      title: "لا يوجد نزيف",
      description: "لا دليل على نزيف داخل الجمجمة أو تأثير كتلي."
    }
  }
  
  const translationsMap = lang === "fr" ? frTranslations : arTranslations
  const translated = translationsMap[finding.title]
  
  if (translated) {
    return { ...finding, title: translated.title, description: translated.description }
  }
  return finding
}

const translateDisease = (disease: Disease, lang: Language): Disease => {
  if (lang === "en") return disease
  
  const frTranslations: Record<string, { name: string; description: string }> = {
    "Chronic Microvascular Ischemia": {
      name: "Ischemie Microvasculaire Chronique",
      description: "Maladie des petits vaisseaux affectant la substance blanche"
    },
    "Age-Related Volume Loss": {
      name: "Perte de Volume Liee a l'Age",
      description: "Atrophie cerebrale attendue pour l'age du patient"
    },
    "Acute Stroke": {
      name: "AVC Aigu",
      description: "Aucune preuve d'evenement ischemique aigu"
    }
  }
  
  const arTranslations: Record<string, { name: string; description: string }> = {
    "Chronic Microvascular Ischemia": {
      name: "نقص التروية الوعائية الدقيقة المزمن",
      description: "مرض الأوعية الصغيرة الذي يؤثر على المادة البيضاء"
    },
    "Age-Related Volume Loss": {
      name: "فقدان الحجم المرتبط بالعمر",
      description: "ضمور دماغي متوقع لعمر المريض"
    },
    "Acute Stroke": {
      name: "سكتة دماغية حادة",
      description: "لا دليل على حدث إقفاري حاد"
    }
  }
  
  const translationsMap = lang === "fr" ? frTranslations : arTranslations
  const translated = translationsMap[disease.name]
  
  if (translated) {
    return { ...disease, name: translated.name, description: translated.description }
  }
  return disease
}

const translateImpression = (impression: string, lang: Language): string => {
  if (lang === "en") return impression
  
  if (lang === "fr") {
    return "L'IRM cerebrale demontre des modifications ischemiques microvasculaires chroniques legeres dans la substance blanche periventriculaire, coherentes avec l'age du patient et son historique clinique. Aucune anomalie intracranienne aigue. Pas de masse, d'hemorragie ou de deplacement de la ligne mediane. Recommandation de correlation clinique et de suivi selon les indications cliniques."
  }
  
  return "يُظهر التصوير بالرنين المغناطيسي للدماغ تغيرات إقفارية وعائية دقيقة مزمنة خفيفة في المادة البيضاء حول البطينين، متوافقة مع عمر المريض وتاريخه السريري. لا توجد تشوهات حادة داخل الجمجمة. لا توجد كتلة أو نزيف أو انزياح في خط الوسط. يُوصى بالارتباط السريري والمتابعة حسب الإشارة السريرية."
}

function generateReportHTML(result: AnalysisResult, language: Language): string {
  const t = translations[language]
  const dir = languageLabels[language].dir
  
  const translatedFindings = result.findings.map(f => translateFinding(f, language))
  const translatedDiseases = result.diseases.map(d => translateDisease(d, language))
  const translatedImpression = translateImpression(result.impression, language)
  
  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case "normal": return "#22c55e"
      case "mild": return "#eab308"
      case "moderate": return "#f97316"
      case "severe": return "#ef4444"
      default: return "#6b7280"
    }
  }

  return `
<!DOCTYPE html>
<html dir="${dir}" lang="${language}">
<head>
  <meta charset="UTF-8">
  <title>${t.title}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { 
      font-family: ${language === 'ar' ? "'Segoe UI', 'Arial', sans-serif" : "'Segoe UI', sans-serif"}; 
      line-height: 1.6; 
      color: #1a1a1a; 
      padding: 40px;
      max-width: 800px;
      margin: 0 auto;
    }
    .header { 
      border-bottom: 3px solid #3b82f6; 
      padding-bottom: 20px; 
      margin-bottom: 30px; 
    }
    .header h1 { 
      color: #3b82f6; 
      font-size: 28px; 
      margin-bottom: 8px; 
    }
    .header .subtitle { 
      color: #6b7280; 
      font-size: 12px; 
    }
    .meta-grid { 
      display: grid; 
      grid-template-columns: repeat(2, 1fr); 
      gap: 15px; 
      margin-bottom: 30px; 
      background: #f8fafc; 
      padding: 20px; 
      border-radius: 8px; 
    }
    .meta-item label { 
      font-size: 12px; 
      color: #6b7280; 
      display: block; 
    }
    .meta-item span { 
      font-weight: 600; 
      color: #1a1a1a; 
    }
    .section { 
      margin-bottom: 30px; 
    }
    .section h2 { 
      color: #3b82f6; 
      font-size: 18px; 
      margin-bottom: 15px; 
      padding-bottom: 8px; 
      border-bottom: 1px solid #e5e7eb; 
    }
    .disease-item { 
      display: flex; 
      justify-content: space-between; 
      align-items: center; 
      padding: 12px; 
      background: #f8fafc; 
      border-radius: 6px; 
      margin-bottom: 10px; 
    }
    .disease-name { 
      font-weight: 500; 
    }
    .disease-desc { 
      font-size: 12px; 
      color: #6b7280; 
    }
    .confidence { 
      padding: 4px 12px; 
      border-radius: 20px; 
      font-size: 12px; 
      font-weight: 600; 
    }
    .finding { 
      padding: 15px; 
      background: #f8fafc; 
      border-radius: 6px; 
      margin-bottom: 12px; 
      border-left: 4px solid; 
    }
    .finding-header { 
      display: flex; 
      justify-content: space-between; 
      align-items: center; 
      margin-bottom: 8px; 
    }
    .finding-title { 
      font-weight: 600; 
    }
    .severity { 
      padding: 2px 8px; 
      border-radius: 4px; 
      font-size: 11px; 
      font-weight: 500; 
    }
    .finding-desc { 
      font-size: 14px; 
      color: #4b5563; 
      margin-bottom: 5px; 
    }
    .finding-location { 
      font-size: 12px; 
      color: #9ca3af; 
    }
    .impression { 
      padding: 20px; 
      background: #eff6ff; 
      border-radius: 8px; 
      font-size: 14px; 
      line-height: 1.8; 
    }
    .disclaimer { 
      margin-top: 40px; 
      padding-top: 20px; 
      border-top: 1px solid #e5e7eb; 
      font-size: 11px; 
      color: #9ca3af; 
      font-style: italic; 
    }
    @media print {
      body { padding: 20px; }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${t.title}</h1>
    <p class="subtitle">${t.generatedBy} - ${new Date().toLocaleDateString()}</p>
  </div>
  
  <div class="meta-grid">
    <div class="meta-item">
      <label>${t.patientId}</label>
      <span>${result.metadata.patientId}</span>
    </div>
    <div class="meta-item">
      <label>${t.studyDate}</label>
      <span>${result.metadata.studyDate}</span>
    </div>
    <div class="meta-item">
      <label>${t.scanType}</label>
      <span>${result.metadata.scanType}</span>
    </div>
    <div class="meta-item">
      <label>Dimensions</label>
      <span>${result.metadata.dimensions}</span>
    </div>
  </div>
  
  <div class="section">
    <h2>${t.aiDetection}</h2>
    ${translatedDiseases.map(disease => {
      const confColor = disease.confidence > 0.7 ? '#fef2f2' : disease.confidence > 0.3 ? '#fefce8' : '#f0fdf4'
      const textColor = disease.confidence > 0.7 ? '#dc2626' : disease.confidence > 0.3 ? '#ca8a04' : '#16a34a'
      return `
      <div class="disease-item">
        <div>
          <div class="disease-name">${disease.name}</div>
          <div class="disease-desc">${disease.description}</div>
        </div>
        <span class="confidence" style="background: ${confColor}; color: ${textColor}">
          ${t.confidence}: ${Math.round(disease.confidence * 100)}%
        </span>
      </div>
    `}).join('')}
  </div>
  
  <div class="section">
    <h2>${t.findings}</h2>
    ${translatedFindings.map(finding => {
      const color = getSeverityColor(finding.severity)
      return `
      <div class="finding" style="border-color: ${color}">
        <div class="finding-header">
          <span class="finding-title">${finding.title}</span>
          <span class="severity" style="background: ${color}20; color: ${color}">
            ${t.severity[finding.severity]}
          </span>
        </div>
        <p class="finding-desc">${finding.description}</p>
        <p class="finding-location">${t.location}: ${finding.location}</p>
      </div>
    `}).join('')}
  </div>
  
  <div class="section">
    <h2>${t.impression}</h2>
    <div class="impression">${translatedImpression}</div>
  </div>
  
  <div class="disclaimer">${t.disclaimer}</div>
</body>
</html>
  `
}

function ReportPreview({ result, language }: { result: AnalysisResult; language: Language }) {
  const t = translations[language]
  const dir = languageLabels[language].dir
  
  const translatedFindings = result.findings.map(f => translateFinding(f, language))
  const translatedDiseases = result.diseases.map(d => translateDisease(d, language))
  const translatedImpression = translateImpression(result.impression, language)
  
  return (
    <div 
      className={cn(
        "bg-white text-black p-6 rounded-lg max-h-[60vh] overflow-y-auto",
        dir === "rtl" && "text-right"
      )}
      dir={dir}
    >
      {/* Header */}
      <div className="border-b-2 border-primary pb-4 mb-6">
        <h1 className="text-2xl font-bold text-primary">{t.title}</h1>
        <p className="text-xs text-gray-500 mt-1">{t.generatedBy}</p>
      </div>
      
      {/* Patient info */}
      <div className="grid grid-cols-2 gap-4 mb-6 text-sm">
        <div>
          <span className="font-medium">{t.patientId}:</span> {result.metadata.patientId}
        </div>
        <div>
          <span className="font-medium">{t.studyDate}:</span> {result.metadata.studyDate}
        </div>
        <div className="col-span-2">
          <span className="font-medium">{t.scanType}:</span> {result.metadata.scanType}
        </div>
      </div>
      
      {/* AI Detection */}
      <div className="mb-6">
        <h2 className="text-lg font-semibold mb-3 text-primary">{t.aiDetection}</h2>
        <div className="space-y-2">
          {translatedDiseases.map((disease, i) => (
            <div key={i} className="flex items-center justify-between py-2 border-b border-gray-100">
              <div>
                <span className="font-medium">{disease.name}</span>
                <p className="text-xs text-gray-500">{disease.description}</p>
              </div>
              <span className={cn(
                "text-sm font-medium px-2 py-1 rounded",
                disease.confidence > 0.7 ? "bg-red-100 text-red-700" :
                disease.confidence > 0.3 ? "bg-yellow-100 text-yellow-700" :
                "bg-green-100 text-green-700"
              )}>
                {t.confidence}: {Math.round(disease.confidence * 100)}%
              </span>
            </div>
          ))}
        </div>
      </div>
      
      {/* Findings */}
      <div className="mb-6">
        <h2 className="text-lg font-semibold mb-3 text-primary">{t.findings}</h2>
        <div className="space-y-3">
          {translatedFindings.map((finding, i) => (
            <div key={i} className="p-3 bg-gray-50 rounded-lg">
              <div className="flex items-center justify-between mb-1">
                <span className="font-medium">{finding.title}</span>
                <span className={cn(
                  "text-xs px-2 py-0.5 rounded-full",
                  finding.severity === "normal" ? "bg-green-100 text-green-700" :
                  finding.severity === "mild" ? "bg-yellow-100 text-yellow-700" :
                  finding.severity === "moderate" ? "bg-orange-100 text-orange-700" :
                  "bg-red-100 text-red-700"
                )}>
                  {t.severity[finding.severity]}
                </span>
              </div>
              <p className="text-sm text-gray-600">{finding.description}</p>
              <p className="text-xs text-gray-400 mt-1">{t.location}: {finding.location}</p>
            </div>
          ))}
        </div>
      </div>
      
      {/* Impression */}
      <div className="mb-6">
        <h2 className="text-lg font-semibold mb-3 text-primary">{t.impression}</h2>
        <p className="text-sm text-gray-700 leading-relaxed">{translatedImpression}</p>
      </div>
      
      {/* Disclaimer */}
      <div className="mt-8 pt-4 border-t border-gray-200">
        <p className="text-xs text-gray-500 italic">{t.disclaimer}</p>
      </div>
    </div>
  )
}

export function ReportPanel({ result }: { result: AnalysisResult }) {
  const [isOpen, setIsOpen] = useState(false)
  const [language, setLanguage] = useState<Language>("fr")
  const [exportFormat, setExportFormat] = useState<ExportFormat>("pdf")
  const [isExporting, setIsExporting] = useState(false)
  const [exportSuccess, setExportSuccess] = useState(false)
  
  const handleExport = async () => {
    setIsExporting(true)
    
    // Generate HTML content
    const htmlContent = generateReportHTML(result, language)
    const filename = `medvision-report-${result.metadata.patientId}-${language}`
    
    if (exportFormat === "pdf") {
      // For PDF, we open in a new window and use print functionality
      const printWindow = window.open('', '_blank')
      if (printWindow) {
        printWindow.document.write(htmlContent)
        printWindow.document.close()
        
        // Wait for content to load then trigger print
        setTimeout(() => {
          printWindow.print()
          setIsExporting(false)
          setExportSuccess(true)
          setTimeout(() => setExportSuccess(false), 3000)
        }, 500)
      } else {
        setIsExporting(false)
      }
    } else {
      // For DOCX, create a proper Word document structure
      const wordContent = `
<!DOCTYPE html>
<html xmlns:o="urn:schemas-microsoft-com:office:office" 
      xmlns:w="urn:schemas-microsoft-com:office:word" 
      xmlns="http://www.w3.org/TR/REC-html40">
<head>
  <meta charset="utf-8">
  <title>${translations[language].title}</title>
  <!--[if gte mso 9]>
  <xml>
    <w:WordDocument>
      <w:View>Print</w:View>
      <w:Zoom>100</w:Zoom>
    </w:WordDocument>
  </xml>
  <![endif]-->
  <style>
    body { font-family: Calibri, sans-serif; font-size: 11pt; }
    h1 { color: #3b82f6; font-size: 18pt; }
    h2 { color: #3b82f6; font-size: 14pt; border-bottom: 1px solid #e5e7eb; padding-bottom: 5pt; }
    .meta { background: #f8fafc; padding: 10pt; margin: 10pt 0; }
    .finding { background: #f8fafc; padding: 10pt; margin: 10pt 0; border-left: 3pt solid #3b82f6; }
    .impression { background: #eff6ff; padding: 15pt; }
    .disclaimer { font-size: 9pt; color: #9ca3af; font-style: italic; margin-top: 20pt; }
  </style>
</head>
<body>
  <h1>${translations[language].title}</h1>
  <p style="color: #6b7280; font-size: 10pt;">${translations[language].generatedBy} - ${new Date().toLocaleDateString()}</p>
  
  <div class="meta">
    <p><strong>${translations[language].patientId}:</strong> ${result.metadata.patientId}</p>
    <p><strong>${translations[language].studyDate}:</strong> ${result.metadata.studyDate}</p>
    <p><strong>${translations[language].scanType}:</strong> ${result.metadata.scanType}</p>
  </div>
  
  <h2>${translations[language].aiDetection}</h2>
  ${result.diseases.map(d => translateDisease(d, language)).map(disease => `
    <p><strong>${disease.name}</strong> - ${translations[language].confidence}: ${Math.round(disease.confidence * 100)}%<br/>
    <span style="color: #6b7280; font-size: 10pt;">${disease.description}</span></p>
  `).join('')}
  
  <h2>${translations[language].findings}</h2>
  ${result.findings.map(f => translateFinding(f, language)).map(finding => `
    <div class="finding">
      <p><strong>${finding.title}</strong> (${translations[language].severity[finding.severity]})</p>
      <p style="color: #4b5563;">${finding.description}</p>
      <p style="color: #9ca3af; font-size: 10pt;">${translations[language].location}: ${finding.location}</p>
    </div>
  `).join('')}
  
  <h2>${translations[language].impression}</h2>
  <div class="impression">
    <p>${translateImpression(result.impression, language)}</p>
  </div>
  
  <p class="disclaimer">${translations[language].disclaimer}</p>
</body>
</html>`

      // Create and download the Word document
      const blob = new Blob(['\ufeff', wordContent], { 
        type: 'application/msword' 
      })
      const url = URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url
      link.download = `${filename}.doc`
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      URL.revokeObjectURL(url)
      
      setIsExporting(false)
      setExportSuccess(true)
      setTimeout(() => setExportSuccess(false), 3000)
    }
  }
  
  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogTrigger asChild>
        <Button className="gap-2">
          <FileText className="w-4 h-4" />
          Generer Rapport
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-4xl">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-primary" />
            Generer un Rapport
          </DialogTitle>
          <DialogDescription>
            Previsualiser et exporter votre rapport d&apos;analyse en plusieurs langues
          </DialogDescription>
        </DialogHeader>
        
        <div className="space-y-4">
          {/* Controls */}
          <div className="flex flex-wrap items-center gap-4">
            {/* Language selector */}
            <div className="flex items-center gap-2">
              <Languages className="w-4 h-4 text-muted-foreground" />
              <Select value={language} onValueChange={(v) => setLanguage(v as Language)}>
                <SelectTrigger className="w-40">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {(Object.keys(languageLabels) as Language[]).map((lang) => (
                    <SelectItem key={lang} value={lang}>
                      <span className="flex items-center gap-2">
                        <span>{languageLabels[lang].flag}</span>
                        <span>{languageLabels[lang].name}</span>
                      </span>
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            
            {/* Format selector */}
            <div className="flex items-center gap-2">
              <FileType className="w-4 h-4 text-muted-foreground" />
              <Select value={exportFormat} onValueChange={(v) => setExportFormat(v as ExportFormat)}>
                <SelectTrigger className="w-32">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="pdf">PDF</SelectItem>
                  <SelectItem value="docx">Word (DOC)</SelectItem>
                </SelectContent>
              </Select>
            </div>
            
            {/* Export button */}
            <Button 
              onClick={handleExport} 
              disabled={isExporting}
              className="gap-2 ml-auto"
            >
              {isExporting ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  Exportation...
                </>
              ) : exportSuccess ? (
                <>
                  <Check className="w-4 h-4" />
                  Telecharge!
                </>
              ) : (
                <>
                  <Download className="w-4 h-4" />
                  Exporter {exportFormat.toUpperCase()}
                </>
              )}
            </Button>
          </div>
          
          {/* Preview */}
          <div className="border rounded-lg overflow-hidden">
            <div className="bg-muted px-4 py-2 border-b flex items-center justify-between">
              <span className="text-sm font-medium">Apercu</span>
              <span className="text-xs text-muted-foreground">
                {languageLabels[language].flag} {languageLabels[language].name}
              </span>
            </div>
            <ReportPreview result={result} language={language} />
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}
